-- Create vin_decoded_data table for decodeVIN2 / 为 decodeVIN2 创建 vin_decoded_data 表
-- Run this on the server database (e.g. sasto2574403) to fix: Table 'sasto2574403.vin_decoded_data' doesn't exist
-- 在服务器数据库（如 sasto2574403）中执行此脚本以修复“表不存在”错误

CREATE TABLE IF NOT EXISTS `vin_decoded_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `vin` varchar(17) NOT NULL,
  `brand_name` varchar(255) DEFAULT NULL,
  `series_name` varchar(255) DEFAULT NULL,
  `model_name` varchar(255) DEFAULT NULL,
  `version` varchar(255) DEFAULT NULL,
  `year` int(4) DEFAULT NULL,
  `fuel_type` varchar(50) DEFAULT NULL,
  `transmission` varchar(50) DEFAULT NULL,
  `drivetrain` varchar(50) DEFAULT NULL,
  `engine_size` decimal(10,2) DEFAULT NULL,
  `engine_cylinders` int(11) DEFAULT NULL,
  `body_type` varchar(100) DEFAULT NULL,
  `doors` int(11) DEFAULT NULL,
  `seats` int(11) DEFAULT NULL,
  `length` decimal(10,2) DEFAULT NULL,
  `width` decimal(10,2) DEFAULT NULL,
  `height` decimal(10,2) DEFAULT NULL,
  `wheelbase` decimal(10,2) DEFAULT NULL,
  `curb_weight` decimal(10,2) DEFAULT NULL,
  `gross_weight` decimal(10,2) DEFAULT NULL,
  `max_power` decimal(10,2) DEFAULT NULL,
  `max_torque` decimal(10,2) DEFAULT NULL,
  `acceleration` decimal(10,2) DEFAULT NULL,
  `mpg_city` decimal(10,2) DEFAULT NULL,
  `mpg_highway` decimal(10,2) DEFAULT NULL,
  `mpg_combined` decimal(10,2) DEFAULT NULL,
  `co2_emissions` decimal(10,2) DEFAULT NULL,
  `exterior_color` varchar(100) DEFAULT NULL,
  `interior_color` varchar(100) DEFAULT NULL,
  `interior_material` varchar(255) DEFAULT NULL,
  `manufacturer` varchar(255) DEFAULT NULL,
  `market_date` date DEFAULT NULL,
  `stop_date` date DEFAULT NULL,
  `front_tyre_size` varchar(100) DEFAULT NULL,
  `rear_tyre_size` varchar(100) DEFAULT NULL,
  `front_brake_type` varchar(100) DEFAULT NULL,
  `rear_brake_type` varchar(100) DEFAULT NULL,
  `parking_brake_type` varchar(100) DEFAULT NULL,
  `data_source` varchar(50) DEFAULT NULL,
  `api_provider` varchar(50) DEFAULT NULL,
  `decoded_at` datetime DEFAULT NULL,
  `language` varchar(10) DEFAULT 'en',
  `model_list` text DEFAULT NULL COMMENT 'Model list (JSON) / 车型列表（JSON）',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `vin` (`vin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
